FROM php:fpm-stretch

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
    git\
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install \
    zip \
    intl \
    mysqli \
    pdo pdo_mysql

    RUN curl -sL https://deb.nodesource.com/setup_13.x -o nodesource_setup.sh
    RUN bash nodesource_setup.sh
    RUN apt-get install nodejs -y
    RUN npm install npm@6.13.0 -g
    RUN command -v node
    RUN command -v npm

    RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
    COPY ./symfony /var/www/symfony
    WORKDIR /var/www/symfony